services:
  api:
    build:
      context: .
      target: development
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app #mount the root directory into the container, so changes to the source code are reflected immediately
      - /usr/src/app/node_modules #exclude the node_modules directory from the mount, so we don't overwrite the production dependencies
    networks:
      - internal-net
  kafka:
    image: apache/kafka:4.3.1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - internal-net

  # event-consumer:
  #   build:
  #     context: .
  #   command: node dist/consumers/event-consumer/app.js
  #   environment:
  #     NODE_ENV: production

networks:
  internal-net:
